- name: printing statements
  hosts: localhost
  connection: local
  tasks:
    - name: print hello world
      debug:
        msg: Hello world
      when: what == "world"

    - name: print hello universe
      debug:
        msg: Hello universe
      when: what == "universe"