- name: printing statements
  hosts: localhost
  connection: local
  tasks:
    - name: print hello world
      debug:
        msg: Fruit name {{item}}
      loops:
        - apple
        - banana
        - grapes
        - orange