- name: frontend
  hosts: all
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: hostname
        use: systemd

    - name: Installing Nginx
      ansible.builtin.yum:
        name: ngnix
        state: latest






    # echo -e "${color}setting the hostname${nocolor}"
    # hostnamectl set-hostname ${component}
    # stat_check $?

    # echo -e "${color}Installing Nginx Server${nocolor}"
    # dnf install nginx -y &>> ${log_file}
    # stat_check $?

    # echo -e "${color}Removing Old App content${nocolor}"
    # rm -rf /usr/share/nginx/html/* &>> ${log_file}
    # stat_check $?

    # echo -e "${color}downloading ${component} Content${nocolor}"
    # curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>> ${log_file}
    # stat_check $?

    # echo -e "${color}Extracting ${component} Content${nocolor}"
    # cd /usr/share/nginx/html 
    # unzip /tmp/${component}.zip &>> ${log_file}
    # stat_check $?

    # # vim /etc/nginx/default.d/roboshop.conf 
    # echo -e "${color}Creating Nginx Reverse Proxy Configuration${nocolor}"
    # cp /home/centos/roboshop-shell/roboshop.conf /etc/nginx/default.d/
    # stat_check $?

    # echo -e "${color}Starting Nginx Server${nocolor}"
    # systemctl enable nginx &>> ${log_file}
    # systemctl restart nginx &>> ${log_file}
    # stat_check $?