- name: frontend
  hosts: all
  become: yes
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: frontend
        use: systemd

    - name: Installing Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Removing old app content
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
    
    - name: downloading frontend Content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Creating Nginx Reverse Proxy Configuration
      ansible.builtin.copy:
        src: /home/centos/learn-ansible/roboshop-ansible/roboshop.conf
        dest: /etc/nginx/default.d/
        follow: yes

    - name: Enabling Nginx Server
      ansible.builtin.service:
        name: nginx
        enabled: yes

    - name: Restarting Nginx Server
      ansible.builtin.service:
        name: nginx
        state: restarted


    # echo -e "${color}setting the hostname${nocolor}"
    # hostnamectl set-hostname ${component}
    # stat_check $?

    # echo -e "${color}Installing Nginx Server${nocolor}"
    # dnf install nginx -y &>> ${log_file}
    # stat_check $?

    # echo -e "${color}Removing Old App content${nocolor}"
    # rm -rf /usr/share/nginx/html/* &>> ${log_file}
    # stat_check $?

    # echo -e "${color}downloading ${component} Content${nocolor}"
    # curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>> ${log_file}
    # stat_check $?

    # echo -e "${color}Extracting ${component} Content${nocolor}"
    # cd /usr/share/nginx/html 
    # unzip /tmp/${component}.zip &>> ${log_file}
    # stat_check $?

    # # vim /etc/nginx/default.d/roboshop.conf 
    # echo -e "${color}Creating Nginx Reverse Proxy Configuration${nocolor}"
    # cp /home/centos/roboshop-shell/roboshop.conf /etc/nginx/default.d/
    # stat_check $?

    # echo -e "${color}Starting Nginx Server${nocolor}"
    # systemctl enable nginx &>> ${log_file}
    # systemctl restart nginx &>> ${log_file}
    # stat_check $?